### ISSUE TITLE
Installing on a Mac using documented command-line fails

### ISSUE THREAD

**Issue by TimothyMDean** [SDGGiesbrecht/Workspace#258]
### Description

I tried to install workspace for the first time, using the command documented in the documentation. Most of the installation seems to work: The appropriate Swift packages are built, and near the end I see a message stating that installation was successful.

However, after everything is built the installation script does some things to add workspace to my path, and the runs `workspace help`. Those path configuration changes are broken, and as a result the final `workspace help` command fails:
```
bash: line 115: workspace: command not found
```

I have looked over the installer script, and it appears to be simply a mistake in the script. There is part of the script that does this:
```
# Register the products.
for tool in tools ; do
```

If I add a `$` before `tools` it works:
```
# Register the products.
for tool in $tools ; do
```

**Comment by SDGGiesbrecht** [comment]
Hi, @TimothyMDean. Thanks for filing a report.

I just [fixed it](https://gist.github.com/SDGGiesbrecht/4d76ad2f2b9c7bf9072ca1da9815d7e2/revisions)—I believe anyway. I tested it locally and it worked properly. Can you verify?

The error was introduced only a few months ago. It snuck by because it does not affect *updates*, so it did not affect existing users. New users experimenting for the first time are the least likely to actually do anything about it if it doesn’t work, so extra special thanks for taking the effort to report it to a stranger!

**Comment by TimothyMDean** [comment]
@SDGGiesbrecht I have just tried it again and your fix works for me. Thanks for the speedy response.
