### ISSUE TITLE
Running refresh on existing projects – unclear behavior

### ISSUE THREAD

**Issue by Jeehut** [SDGGiesbrecht/Workspace#600]
### Question

I just ran `workspace refresh` on [HandySwift](https://github.com/Flinesoft/HandySwift) and the first thing which happened was basically no files changed, but three script files created (`Refresh (Linux).sh`, `Refresh (macOS).command` and `Validate(macOS).command`). First question: What are these files for? Their purpose isn't documented anywhere ... also, can I place them into a subfolder? I'd rather not have so many files on the root level ...

Next, because I wanted to make HandySwift actually a cross-platform library and relies on SwiftPM, I removed the `.xcodeproj` and `.xcworkspace` folders entirely to move to a `Package.swift` based project. Then I ran `workspace refresh` again. This time, nothing happened. I started wondering what the command is doing anyways, I'm not sure if I did something wrong or if this is actually the expected behavior.

Then, I ran `workspace test` which ran all the tests for all Apple platforms (I'm assuming because I'm on a Mac) except watchOS, so I'm wondering why watchOS isn't tested, too, because it's less common or is there another reason? (OK, that question maybe is off-topic ...)

After running the tests though I had a `.swiftpm` folder full of test results which were showing in my unstages changes in Git, even running `workspace refresh` one more time didn't change that. I would expect a `refresh` command to adjust a project in some ways, for example by adding the `.swiftpm` folder to the `.gitignore` file if it's not there yet (I'm assuming that's the best practice here).

### Documentation Suggestion

Make it more clear what exactly `refresh` does both in empty projects but also in existing projects. For example, if I didn't have a LICENSE file, would it add one? (Ok, I just tried, it doesn't – I'd expect that, too...)

**Comment by SDGGiesbrecht** [comment]
> First question: What are these files for?

If they are checked in, someone who clones can double click them to have Workspace do its thing without installing on the system. (It will temporarily install itself inside `.build`, where it will disappear with the repository when the repository is deleted.) “Just double‐click `Refresh (macOS).command` before you start, and `Validate (macOS).command` before you make a pull request.” become the only instructions a new contributor needs.

They can also be useful as a means to fetch and run the version of Workspace expected by the project even if it is different that the one currently installed on your development device.

Experienced users rarely touch them once they because familiar with the command line, because individual invocations are usually much faster.

The scripts can be removed entirely by configuring [`configuration.provideWorkflowScripts = false`](https://sdggiesbrecht.github.io/Workspace/🇬🇧EN/Types/WorkspaceConfiguration/Properties/provideWorkflowScripts.html).

> Next, because I wanted to make HandySwift actually a cross-platform library and relies on SwiftPM, I removed the .xcodeproj and .xcworkspace folders entirely to move to a Package.swift based project. Then I ran workspace refresh again. This time, nothing happened. I started wondering what the command is doing anyways, I'm not sure if I did something wrong or if this is actually the expected behavior.

Massively writing into project files scares users who aren’t familiar with a tool yet. Instead, as much as possible, the defaults don’t write into existing files. For those wanting to live dangerously and try everything it can do all at once, there is [`configuration.optIntoAllTasks()`](https://sdggiesbrecht.github.io/Workspace/🇬🇧EN/Types/WorkspaceConfiguration/Methods/optIntoAllTasks().html).

> I'm wondering why watchOS isn't tested, too, because it's less common or is there another reason?

Xcode provides no means to write tests for watchOS (unless it’s new to Xcode 12 and I missed it). You have to wrap any XCTest code with `#if !os(watchOS)` anyway. As soon as Xcode supports it, watchOS will be tested too. Until then, the best Workspace can do is build all the modules and verify there are no compiler failures.

> After running the tests though I had a .swiftpm folder full of test results which were showing in my unstages changes in Git, even running workspace refresh one more time didn't change that. I would expect a refresh command to adjust a project in some ways, for example by adding the .swiftpm folder to the .gitignore file if it's not there yet (I'm assuming that's the best practice here).

Workspace will make sure it is covered by `.gitignore`, provided that `.gitignore` has been placed under Workspace’s control ([`configuration.git.manage = true`](https://sdggiesbrecht.github.io/Workspace/🇬🇧EN/Types/GitConfiguration/Properties/manage.html), or `optIntoAllTasks()`).

**Comment by SDGGiesbrecht** [comment]
The improvements to the `help` subcommand are included in 0.35.3.
