### ISSUE TITLE
Add command to generate configuration file with defaults

### ISSUE THREAD

**Issue by Jeehut** [SDGGiesbrecht/Workspace#601]
### Description

I just ran `workspace document` in an existing project to see what it does, but it failed to generate documentation with this output:

```shell
No original copyright date is specified.
(Configure it under “documentation.api.yearFirstPublished”.)

There are no localisations specified. (documentation.localisations)

✗ Failed to generate documentation. (See ⌘F ‘§1’)

‘HandySwift’ fails validation.
```

To me this looks like a `Workspace.swift` configuration file is actually required for this feature to work. Thus I'd expect there to be a simple way of creating one, for example via `workspace configure`. 

### Availability to Help

I **would not like to help** implement it.

### Design Thoughts

I would at least generate an example file with sensible defaults. There might be even a questionnaire-like variant (similar to how Fastlane is configured) to setup the most important options, including copyright date and loclalisations, it seems.

**Comment by SDGGiesbrecht** [comment]
This is a good idea.

**Comment by Jeehut** [comment]
In that case,at least for the questionnaire, I would suggest to provide a few different paths given that Workspace has so many aspects to it. The question would be which configurations paths we provide and what they would cover. On first thought, I think it would make sense to have these four:

1. Minimal: Only asks for whatever is needed at minimum for a good unintrusive configuration that won't affect a project much.
2. Custom: Will ask for all recommended features to turn them on/off and to configure their important parts.
3. Recommended: Will turn on all recommended features and only ask for configuring their important parts.
4. Full: Will turn on all features (except if there were any mutually exclusive ones) and ask for their main configuration.

The next question then would be, what featues can be considered "Minimal/Highly Recommended", what "Recommended/On by Default" and what "Optional/Opt-In"? Specifying one of these options for every feature and also adding minimum required configuration per feature will make this questionnaire-mode quite automatable.

**Comment by SDGGiesbrecht** [comment]
Okay, the more pressing Swift 5.3‐related updates are complete and have some time to consider this more.

***

First, for the sake of defining how those four levels correspond to the status quo:

1. > Minimal: Only asks for whatever is needed at minimum for a good unintrusive configuration that won't affect a project much.

    That is essentially the definition of the default configuration used when no configuration file exists. Tasks are active if they won’t change project files (e.g. test coverage, documentation coverage validation). Tasks are active if they would only write to a file if explicitly triggered by some annotation in the source (e.g. documentation, example synchronization).

    The default/implicit configuration is identical to this explicit configuration:

    ```swift
    // Workspace.swift
    import WorkspaceConfiguration
    let configuration = WorkspaceConfiguration()
    ```

2. > Custom: Will ask for all recommended features to turn them on/off and to configure their important parts.

    No such functionality yet exists. The nearest equivalent action a user could take would be to read through [the list of configuration properties in the documentation](https://sdggiesbrecht.github.io/Workspace/🇬🇧EN/Types/WorkspaceConfiguration.html).

3. > Recommended: Will turn on all recommended features and only ask for configuring their important parts.

    > Full: Will turn on all features (except if there were any mutually exclusive ones) and ask for their main configuration.

    These two are currently identical. There has so far never really been such thing as an unrecommended feature.

    At times features have spent a few versions in deprecation before they were fully removed, but that was only to provide more time for projects to switch to a better replacement feature. I don’t think having templates for deprecated features is a good idea.

    The current intent for such a configuration is this:

    ```swift
    // Workspace.swift
    import WorkspaceConfiguration
    let configuration = WorkspaceConfiguration()
    configuration.optIntoAllTasks()

    // ...then some metadata not handled by the package manifest (see next section)...
    ```

***

The current exhaustive list of recommended metadata falls into two categories:

1. Metadata specific to the package:
   ```swift
    configuration.documentation.currentVersion = Version(1, 0, 0)

    configuration.documentation.projectWebsite = URL(string: "some.project/site")!
    configuration.documentation.documentationURL = URL(string: "some.documentation/url")!
    configuration.documentation.api.yearFirstPublished = 2020
    configuration.documentation.repositoryURL = URL(string: "some.git/repository")!
   ```
2. Metadata likely shared across an organization or among a family of packages:
    ```swift
    configuration.documentation.localizations = ["en"]

    configuration.documentation.primaryAuthor = "someone or other"
    configuration.gitHub.administrators = ["some GitHub username"]

    configuration.licence.licence = .apache2_0

    configuration.documentation.about["en"] = Markdown("This package is funded by so‐and‐so.")
    ```

***

However, none of the shared metadata really belong in the configuration file itself (unless it really is a single package in isolation). Duplicating that information in several configurations is holding it wrong. The truly recommended way of configuring Workspace looks like this:

```swift
// Workspace.swift

import WorkspaceConfiguration
import MyOrganizationConfiguration // PackageName, the.url/to/it, 1.0.0, ModuleName
//                                    ↑ (this will actually be fetched, built and imported)

let configuration = WorkspaceConfiguration()
configuration.setMyOrganizationDefaults() // Supplied by MyOrganizationConfiguration

configuration.documentation.currentVersion = Version(1, 0, 0)

configuration.documentation.projectWebsite = URL(string: "some.project/site")!
configuration.documentation.documentationURL = URL(string: "some.documentation/url")!
configuration.documentation.api.yearFirstPublished = 2020
configuration.documentation.repositoryURL = URL(string: "some.git/repository")!

configuration.applyMyOrganizationDerivedProperties() // Supplied by MyOrganizationConfiguration
```

***

After laying that out I am no longer sure a generation command is wise.

The first reason is that it cannot create a _good_ configuration. The code snip‐it in the previous section is not viable without actually publishing the other package. It would either generate a configuration that defies recommendations and steers new users away from best practice or it would generate a configuration that doesn’t actually work immediately.

The second reason is that it seems to encroach on an axiom we have (around here anyway), that _templates are inherently bad_. They result in dissociated duplicates that inevitably fall out of sync; dynamic derivation should always be used instead. This was one of the reasons Swift was chosen as the language of the configuration file, and why the recommended starter configurations are vended as `init()` and `optIntoAllTasks()` instead of provided as separate templates. If recommendations change, your configuration stays up to date when you update Workspace. If they were templates, you would have to notice the change and then either overwrite the old configuration with the new template and fill it in all over again, or analyze the difference to apply it manually to your configuration.

***

I still think there is a discoverability weakness here, I just suspect configuration generator command might not be the best solution. Some of the questions on my mind are:

- Is a user likely to encounter the missing setting messages before he knows what a configuration is and where it goes?
- Are the hints sufficient, or can something be made more clear?
- Are some sort of documentation links in order?
- Would it be helpful if any of the information earlier in this post need to be outlined more clearly somewhere in the documentation?

***

Any other observations (from anyone) while I continue to consider this?

**Comment by Jeehut** [comment]
@SDGGiesbrecht I think it's really important that this project provides benefits to users already with just investing 1-2 minutes documentation reading times and additional 1-2 minutes setting up the first useful things in a project. 

If it takes longer than that (either 5 minute documentation read time or 10-15 minutes configuration time) to even get the first real benefit, then I fear adoption will never get very high and it will stay a pro tool for some edge cases.

The reason why I had mentioned Fastlane is because that also is a tool which takes time to understand & configure correctly, but the "interview" setup mode made many of its features easy to test out even without understanding much in a short amount of time, showing its potential and therefore convincing people that it's probably worth investing the additional time to use it properly.

**Comment by SDGGiesbrecht** [comment]
I still think a set‐up wizard would encourage bad habits. However, I have taken the following comment to heart, and believe it was a very wise observation.

> I think it's really important that this project provides benefits to users already with just investing 1-2 minutes documentation reading times and additional 1-2 minutes setting up the first useful things in a project.

As such, work has been done over the last month to make this becomes a reality.

In the past, Workspace failed early if information was missing. For example, “You haven’t told me whether the project should be documented in English or in Chinese. I cannot continue.” The philosophy for this class of settings was:

1. There is no sensible, fair or safe default.
2. If it’s going to fail, the user would probably rather know immediately than after wasting several minutes waiting.

This favoured the experienced user, who would only encounter the errors after forgetting to do something, and who would immediately understand the error and know how to fix it. But it left the new user high and dry, needing to face a lot of dead ends before anything would work.

Going forward, for the sake of new users, **under a default configuration, Workspace should always complete any task it was ordered to do, so that the user can see results immediately**—even if those results are unlikely to be quite what the user will eventually settle on. If a setting is absolutely necessary in order to continue, Workspace will fall back on a sample and throw a warning—without stopping.

For example, `workspace document` will fall back on the system language in order to produce some documentation for the user to see, but will also display a prominent warning explaining that the results may differ from one workstation to another until the project is configured with a particular localization.

In addition, every error or warning that indicates an issue with the configured settings will now contain a link to [the documentation about the configuration file](https://sdggiesbrecht.github.io/Workspace/🇬🇧EN/Types/WorkspaceConfiguration.html), which describes what it is and where it goes and contains an example. That way if it happens to be the first time a user hears of a configuration, he can quickly find the best source of answers to his questions without needing to hunt for them with an internet search.

These changes are believed to be complete and will be included in the next release. (If any such settings were missed while combing the source files, they will also be fixed whenever they are reported.)
